name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
      continue-on-error: true

    - name: Deploy (test passed)
      if: success()
      run: echo "Deployed"

    - name: deploy (tests failed)
      if: failure()
      run: echo "tests failed. Stoping deployment." && exit 1
